/**
 * @fileoverview DOM element references for UI manipulation across different game phases.
 */

import { GAME_PHASE } from "./config.js";

/** Mapping of game phases to corresponding screen element IDs. */
export const SCREEN_BY_PHASE = {
  [GAME_PHASE.MAIN_MENU]: "screen-main-menu",
  [GAME_PHASE.CHARACTER_CREATION]: "screen-character",
  [GAME_PHASE.HUB]: "screen-hub",
  [GAME_PHASE.SHOP]: "screen-shop",
  [GAME_PHASE.EXPLORATION]: "screen-exploration",
  [GAME_PHASE.BATTLE]: "screen-battle",
  [GAME_PHASE.SETTINGS]: "screen-settings",
  [GAME_PHASE.LOAD]: "screen-load",
  [GAME_PHASE.ENDING]: "screen-ending"
};

/** Object containing cached references to DOM elements for efficient access. */
export const dom = {
  sceneContainer: document.getElementById("scene-container"),
  eventBanner: document.getElementById("event-banner"),
  toast: document.getElementById("toast"),
  screens: {
    menu: document.getElementById("screen-main-menu"),
    character: document.getElementById("screen-character"),
    hub: document.getElementById("screen-hub"),
    shop: document.getElementById("screen-shop"),
    exploration: document.getElementById("screen-exploration"),
    battle: document.getElementById("screen-battle"),
    settings: document.getElementById("screen-settings"),
    load: document.getElementById("screen-load"),
    ending: document.getElementById("screen-ending")
  },
  startGameBtn: document.getElementById("start-game-btn"),
  loadGameBtn: document.getElementById("load-game-btn"),
  settingsBtn: document.getElementById("settings-btn"),
  exitBtn: document.getElementById("exit-btn"),
  playerNameInput: document.getElementById("player-name-input"),
  classOptions: document.getElementById("class-options"),
  classSummary: document.getElementById("class-summary"),
  pointsRemaining: document.getElementById("points-remaining"),
  statPointGrid: document.getElementById("stat-point-grid"),
  confirmCharacterBtn: document.getElementById("confirm-character-btn"),
  backFromCharacterBtn: document.getElementById("back-from-character-btn"),
  hubPlayerName: document.getElementById("hub-player-name"),
  hubGold: document.getElementById("hub-gold"),
  hubBosses: document.getElementById("hub-bosses"),
  hubPartySize: document.getElementById("hub-party-size"),
  hubPartyRoster: document.getElementById("hub-party-roster"),
  tavernRoomButtons: document.getElementById("tavern-room-buttons"),
  exploreBtn: document.getElementById("explore-btn"),
  openShopBtn: document.getElementById("open-shop-btn"),
  saveGameBtn: document.getElementById("save-game-btn"),
  backToMenuBtn: document.getElementById("back-to-menu-btn"),
  shopMemberSelect: document.getElementById("shop-member-select"),
  weaponList: document.getElementById("weapon-list"),
  spellList: document.getElementById("spell-list"),
  backToHubFromShopBtn: document.getElementById("back-to-hub-from-shop-btn"),
  enemyName: document.getElementById("enemy-name"),
  enemyStats: document.getElementById("enemy-stats"),
  enemyHpFill: document.getElementById("enemy-hp-fill"),
  battleLog: document.getElementById("battle-log"),
  battleActionBtns: Array.from(document.querySelectorAll(".battle-action-btn")),
  leaveBattleBtn: document.getElementById("leave-battle-btn"),
  battleTextbox: document.getElementById("battle-textbox"),
  battleNextRow: document.getElementById("battle-next-row"),
  battleNextBtn: document.getElementById("battle-next-btn"),
  battleMenu: document.getElementById("battle-menu"),
  battleLeaderName: document.getElementById("battle-leader-name"),
  playerSprite: document.getElementById("player-sprite"),
  enemySprite: document.getElementById("enemy-sprite"),
  playerHpFill: document.getElementById("player-hp-fill"),
  playerHpText: document.getElementById("player-hp-text"),
  enemyHpText: document.getElementById("enemy-hp-text"),
  encounterRateSlider: document.getElementById("encounter-rate-slider"),
  encounterRateValue: document.getElementById("encounter-rate-value"),
  backFromSettingsBtn: document.getElementById("back-from-settings-btn"),
  loadInfo: document.getElementById("load-info"),
  loadSlotBtn: document.getElementById("load-slot-btn"),
  backFromLoadBtn: document.getElementById("back-from-load-btn"),
  endingTitle: document.getElementById("ending-title"),
  endingSummary: document.getElementById("ending-summary"),
  restartBtn: document.getElementById("restart-btn"),
  hudLocation: document.getElementById("hud-location"),
  hudEncounter: document.getElementById("hud-encounter"),
  hudGold: document.getElementById("hud-gold"),
  hudBosses: document.getElementById("hud-bosses"),
  returnHubBtn: document.getElementById("return-hub-btn")
};
